### ISSUE TITLE
arbitrary precision with Convex.jl

### ISSUE THREAD

**Issue by LaurentLessard** [ericphanson/SDPAFamily.jl#35]
I'm trying to solve an SDP with arbitrary precision in `Convex.jl`. Using code borrowed from the `high_precision_test.jl` file and the README example:
```Julia
opt = SDPAFamily.Optimizer(
        presolve = true,
        params = (  epsilonStar = 1e-300, # constraint tolerance
                    epsilonDash = 1e-300, # normalized duality gap tolerance
                    precision = 2000 # arithmetric precision used in sdpa_gmp
                ))
setprecision(2000) do
    y = Semidefinite(3)
    p = maximize(eigmin(y), tr(y) <= 5; numeric_type = BigFloat)
    solve!(p, () -> opt )
    @show p.optval
end
```
The output is correct to 1e-293, which is great, but I was curious as to what might happen if I tried to get even more precision. If I try to set epsilonStar to 1e-400, the solver throws the error: `ArgumentError: epsilonStar > 0 violated`. I tried writing `epsilonStar = big(1e-400)` instead, but then the error is `TypeError: in keyword argument epsilonStar, expected Float64, got BigFloat`.

Is this a fundamental limitation of SDPA-GMP or is there a way around this problem?

Edit: answered my original question, replaced it with a follow-up!

**Comment by ericphanson** [comment]
Good question, I don't think that's a fundamental limitation, although to be honest I haven't tried to go to higher precision than that example. The issue here is that we store all the parameters as Float64's:

https://github.com/ericphanson/SDPAFamily.jl/blob/c8ed970afc6fc77c1d52c7b5d683605f893a9ad2/src/params.jl#L55-L63

We should allow other ways to store them; I think then this would work.

**Comment by ericphanson** [comment]
In an hour or so when SDPAFamily v0.2.2 comes out, this should work!

```julia
    opt = () -> SDPAFamily.Optimizer(
        presolve = true,
        params = (  epsilonStar = big"1e-600", # constraint tolerance
                    epsilonDash = big"1e-600", # normalized duality gap tolerance
                    precision = 2000, # arithmetric precision used in sdpa_gmp
                    maxIteration = 1000
                ))
setprecision(2000) do
    y = Semidefinite(3)
    p = maximize(eigmin(y), tr(y) <= 5; numeric_type = BigFloat)
    solve!(p, opt)
    @show p.optval - big(5)/3
    @test p.optval ≈ big(5)/3 atol=big"1e-600"
end
```

Note you need to pass the settings as BigFloats if you want really high precision, e.g. `big"1e-600" as used here; otherwise, they are interpreted as usual 64-bit Float64 at which point they already round to zero (before then getting converted to BigFloat 0s).
